version: '2.1'
services:
     elasticsearch:
       build:
        context: elasticsearch/
        args:
          ELK_VERSION: $ELK_VERSION
       volumes:
          # Used to save container state
          - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
       environment:
          # Without specifying exact parameters Elastic search fails due to memory issues in docker
          ES_JAVA_OPTS: "-Xms1024m -Xmx1024m"
       ports:
          - "5000:5000"
          - "9600:9600"
          # this port will be used by fluentD to forward messages
          - "9200:9200"
       networks:
           docker-efk:

     kibana:
       build:
        context: kibana/
        args:
          ELK_VERSION: $ELK_VERSION
       ports:
          # At this port Kibana will be available on the host environment, i.e. http://localhost:5601
          - "5601:5601"
       volumes:
          - ./kibana/config/:/usr/share/kibana/config:ro
       environment:
          - "ELASTICSEARCH_URL=http://elasticsearch:9200"
          # In case of X-Pack or any kind of security will be used, specify admin creds here
          - "ELASTICSEARCH_USERNAME=''"
          - "ELASTICSEARCH_PASSWORD=''"
       networks:
          - docker-efk
       depends_on:
          - elasticsearch

networks:
  docker-efk:
    driver: bridge